### ISSUE TITLE
error: command 'aarch64-linux-gnu-gcc' failed with exit status 1

### ISSUE THREAD

**Issue by luyao777** [chaoyuaw/pytorch-coviar#51]
![](https://img.shields.io/badge/error%20-aarch64-red.svg)
Hi, there are some problems when I tried `sudo bash install.sh` in data_loader:
> coviar_data_loader.c:586:15: error: variable ‘coviarmodule’ has initializer but incomplete e type
static struct PyModuleDef coviarmodule = {

 > coviar_data_loader.c:587:5: error: ‘PyModuleDef_HEAD_INIT’ undeclared here (not in a function)
PyModuleDef_HEAD_INIT,

> error: command 'aarch64-linux-gnu-gcc' failed with exit status 1

And I have tried the method mentioned in #33 
But it still doesn't work

Do you have any suggestions?
Thanks!  :blush:

**Comment by luyao777** [comment]
![](https://img.shields.io/badge/build-passing-brightgreen.svg)
According to the [Stackoverflow Answer](https://stackoverflow.com/questions/32295927/failed-c-extension-compilation-for-python)
> you are trying to build with using python2.7 and some of the definitions (PyModuleDef_HEAD_INIT) belongs to >= python3. And there may be a copy paste error on static struct PyModuleDef hellomodule definition. "," is missing after each parameter. – seartun

I modified the `install.sh` in data_loader:
```bash
rm -rf build
python3 setup.py build_ext
python3 setup.py install --user
```
It worked! :tada: :tada:

**Comment by Dreamer312** [comment]
您好呢老哥，我编译的时候也遇到了问题，我是从git上下载的ffmpeg，编译，然后默认安装到了 /usr/local/lib, 然后我改了setup
extra_link_args=['-lavutil', '-lavcodec', '-lavformat', '-lswscale', '-L/usr/local/lib/']
不过似乎不能编译，还是我哪里搞错了，没有太懂他说的setup应该怎么改路径
